import React, {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet';
import {useAuth} from '../helpers/useAuth';
import {PasswordLoginForm} from '../components/PasswordLoginForm';
import {PasswordRegisterForm} from '../components/PasswordRegisterForm';
import {Input} from '../components/Input';
import {Textarea} from '../components/Textarea';
import {Button} from '../components/Button';
import {postStudio} from '../endpoints/studio_POST.schema';
import {renderRecipeCard} from '../helpers/renderRecipeCard';
import styles from './studio.module.css';
const download=(name:string,blob:Blob)=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);};
export default function Studio(){
 const {authState,logout}=useAuth();const qc=useQueryClient();const [register,setRegister]=useState(false),[url,setUrl]=useState(''),[instructions,setInstructions]=useState(''),[pasted,setPasted]=useState(''),[current,setCurrent]=useState<any>(null),[edit,setEdit]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const allowed=authState.type==='authenticated'&&authState.user.role==='admin';
 const rows=useQuery({queryKey:['recipe-drafts',authState.type==='authenticated'?authState.user.id:0],queryFn:()=>postStudio({action:'list'}),enabled:allowed,retry:false});
 const select=(r:any)=>{setCurrent(r);setEdit(JSON.stringify(r.recipe,null,2));setNotice('');};
 const generate=useMutation({mutationFn:()=>postStudio({action:'generate',url,instructions,pasted}),onSuccess:r=>{select(r.record);qc.invalidateQueries({queryKey:['recipe-drafts']});},onError:e=>setNotice(e.message)});
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn();await qc.invalidateQueries({queryKey:['recipe-drafts']});}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const draft=current?JSON.parse(edit||'{}'):null;
 const field=(key:string,value:any)=>setEdit(JSON.stringify({...draft,[key]:value},null,2));
 const save=()=>run(async()=>{const r=await postStudio({action:'save',id:current.id,revision:current.revision,recipe:JSON.parse(edit)});select(r.record);setNotice('Saved privately. This recipe is available in your signed-in library.');});
 const generateImage=()=>run(async()=>{const r=await postStudio({action:'image',id:current.id,revision:current.revision});select(r.record);setNotice('Original image generated and stored.');});
 const card=()=>run(async()=>{if(edit!==JSON.stringify(current.recipe,null,2))throw Error('Save your edits before exporting the card.');const r=await postStudio({action:'asset',id:current.id,revision:current.revision});const read=async(path:string)=>{const response=await fetch(path);if(!response.ok)throw Error('Card asset failed to load');return new Uint8Array(await response.arrayBuffer());};const [regular,bold,logo,hero]=await Promise.all(['/_cdn/static/0e9c3c53-7649-4723-ae87-364370b32563-recipe-DejaVuSans.ttf','/_cdn/static/c62b0043-5828-43d2-851c-500712e98c80-recipe-DejaVuSans-Bold.ttf','/_cdn/static/migration-40d8d46-assets-bloody_dave_logo.png',r.imageUrl!].map(read));const bytes=await renderRecipeCard({recipe:current.recipe,id:current.recipeId||'BD-PENDING',regular,bold,logo,hero});download((current.recipeId||current.id)+'.pdf',new Blob([bytes as BlobPart],{type:'application/pdf'}));setNotice('Two-page A4 landscape PDF exported. Print at 100%, double-sided, flip on short edge.');});
 return <main className={styles.page}><Helmet><title>Recipe Studio — Bloody Dave</title></Helmet><header className={styles.header}><Link to="/">← Recipes</Link><h1>Recipe Studio</h1>{authState.type==='authenticated'&&<Button variant="secondary" onClick={()=>logout()}>Sign out</Button>}</header>
 {authState.type==='loading'?<p>Loading your account…</p>:authState.type==='unauthenticated'?<section className={styles.panel}><h2>{register?'Create your Studio account':'Sign in to Studio'}</h2>{register?<PasswordRegisterForm/>:<PasswordLoginForm/>}<Button variant="link" onClick={()=>setRegister(!register)}>{register?'Already have an account? Sign in':'Create an account'}</Button><p>New accounts need owner approval before using generation.</p></section>:!allowed?<section className={styles.panel}><h2>Account created</h2><p>Your Studio access needs to be enabled by the owner. Your recipes remain private.</p></section>:<>
 <section className={styles.panel}><h2>URL to recipe</h2><label>Source URL<Input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Requested changes<Textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Optional: serve four, replace an ingredient…"/></label><details><summary>Paste source text if the website blocks access</summary><Textarea value={pasted} onChange={e=>setPasted(e.target.value)} rows={8}/></details><Button disabled={generate.isPending||busy||!url} onClick={()=>generate.mutate()}>{generate.isPending?'Reading source and preparing draft…':'Generate draft'}</Button></section>
 <p className={styles.status} role="status">{notice||rows.error?.message}</p>
 <div className={styles.columns}><section className={styles.panel}><h2>Your recipes</h2>{rows.isFetching&&<p>Loading recipes…</p>}{!rows.data?.records?.length&&!rows.isFetching&&<p>No drafts yet. Paste a recipe URL above.</p>}{rows.data?.records?.map(r=><Button key={r.id} variant="secondary" onClick={()=>select(r)}>{r.recipe.title} · {r.state}</Button>)}<Button variant="outline" onClick={()=>run(async()=>{const data=await postStudio({action:'export'});download('bloody-daves-studio-backup.json',new Blob([JSON.stringify({format:'bloody-daves-studio-backup',version:1,exportedAt:new Date().toISOString(),records:data.records},null,2)],{type:'application/json'}));setNotice('Studio backup exported, including source provenance.');})}>Export Studio backup</Button><label>Restore Studio backup<Input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{if(f.size>10000000)throw Error('Backup exceeds 10 MB.');const data=JSON.parse(await f.text());if(data.format!=='bloody-daves-studio-backup'||data.version!==1)throw Error('Invalid Studio backup.');const r=await postStudio({action:'restore',records:data.records});setNotice(`Restored ${r.restored}; unchanged ${r.skipped}.`);});}}/></label></section>
 {current&&<section className={styles.panel}><h2>Review draft</h2><p><a href={current.recipe.source_url} target="_blank" rel="noreferrer">Original source</a> · {current.sourceFacts.extraction_method}</p><p>Ingredients, servings and method edits remove inherited nutrition. Save before generating the card.</p>{['title','subtitle','hook','serves','prep_time','cook_time','total_time','cuisine','protein','allergens','bloody_dave_quote'].map(key=><label key={key}>{key.replaceAll('_',' ')}<Input value={draft[key]||''} onChange={e=>field(key,e.target.value)}/></label>)}{['buy','pantry'].map(key=><label key={key}>{key==='buy'?'Buy ingredients — one per line':'Pantry — one per line'}<Textarea value={(draft[key]||[]).join('\n')} rows={6} onChange={e=>field(key,e.target.value.split('\n'))}/></label>)}{draft.method.map((step:any,i:number)=><div key={i}><label>Step {i+1} heading<Input value={step.heading} onChange={e=>field('method',draft.method.map((x:any,j:number)=>i===j?{...x,heading:e.target.value}:x))}/></label><label>Instructions<Textarea value={step.directions} rows={4} onChange={e=>field('method',draft.method.map((x:any,j:number)=>i===j?{...x,directions:e.target.value}:x))}/></label></div>)}<p>Nutrition: {draft.nutrition}</p><div className={styles.actions}><Button disabled={busy} onClick={save}>Save recipe</Button><Button disabled={busy||!current} onClick={generateImage}>{current.recipe.hero_image?'Image ready':'Generate original image'}</Button><Button disabled={busy||!current.recipe.hero_image} onClick={card}>Export landscape card</Button></div><p>{busy?'Working…':'Original source hash and capture time are retained with this draft.'}</p></section>}</div><p className={styles.status}>Private beta: saved recipes use stable beta IDs. Publishing to the shared production collection remains disabled until migration checks pass.</p></>}
 </main>;
}
